---
version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - nonamedreturns
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/goccy/go-yaml
            - github.com/spacecafe/go-parts
        tests:
          list-mode: strict
          files:
            - $test
          allow:
            - $gostd
            - github.com/spacecafe/go-parts
            - github.com/stretchr/testify
    funcorder:
      constructor: true
      struct-method: true
      alphabetical: true
    gocritic:
      enable-all: true
    gocyclo:
      min-complexity: 20
    govet:
      enable-all: true
    tagliatelle:
      case:
        extended-rules:
          json:
            case: goCamel
          yaml:
            case: goCamel
    varnamelen:
      check-return: true
      check-type-param: true
      ignore-names:
        - ctx
        - err
        - id
        - ok
        - tt
      ignore-decls:
        - t testing.T
        - e error
        - i int
        - const C
        - T any
        - m map[string]int
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
run:
  allow-parallel-runners: true
  relative-path-mode: gomod
  build-tags:
    - with_yaml
...
